# Generated by Django 2.2.1 on 2019-05-22 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeGroup', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62, unique=True)),
                ('picture', models.ImageField(unique=True, upload_to='memes')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('dateOfDeath', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=254)),
                ('public', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('adminClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeRater.MemeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=30)),
                ('dankScale', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeRater.Meme')),
            ],
        ),
    ]
