# Generated by Django 2.2 on 2019-05-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0002_auto_20190515_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='description',
            field=models.TextField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
