# Generated by Django 2.2 on 2019-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0003_meme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='picture',
            field=models.ImageField(unique=True, upload_to='memes'),
        ),
    ]
