# Generated by Django 2.2 on 2019-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0005_auto_20190516_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='memeClass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='public',
            field=models.CharField(default='nic', max_length=14),
        ),
    ]
