# Generated by Django 2.2 on 2019-05-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0006_auto_20190516_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='public',
            field=models.CharField(default='True', max_length=6),
        ),
    ]
