# Generated by Django 2.2 on 2019-05-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0008_auto_20190516_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeClass', models.CharField(max_length=30)),
                ('dankScale', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='meme',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='memeClass',
        ),
        migrations.AddField(
            model_name='meme',
            name='additional',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='memeRater.MemeAdditional'),
            preserve_default=False,
        ),
    ]
