# Generated by Django 2.2 on 2019-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0009_auto_20190517_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeadditional',
            name='dankScale',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='memeadditional',
            name='memeClass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
