# Generated by Django 2.2 on 2019-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0011_auto_20190517_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='additional',
        ),
        migrations.AddField(
            model_name='meme',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MemeAdditional',
        ),
    ]
