# Generated by Django 2.2 on 2019-05-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0012_auto_20190517_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=30)),
                ('dankScale', models.IntegerField(default=5)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeRater.Meme')),
            ],
        ),
    ]
