# Generated by Django 2.2 on 2019-05-17 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dankScale',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
