# Generated by Django 2.2.1 on 2019-05-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0014_auto_20190518_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memeGroup', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='adminClass',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='memeRater.MemeGroup'),
            preserve_default=False,
        ),
    ]
