# Generated by Django 2.2.1 on 2019-05-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeRater', '0015_auto_20190519_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='adminClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeRater.MemeGroup'),
        ),
    ]
